export interface Elements {
  "engine-status": HTMLElement;
  "observatory": HTMLElement;
  "metric-stars": HTMLElement;
  "metric-periods": HTMLElement;
  "metric-median": HTMLElement;
  "metric-catalogues": HTMLElement;
  "metric-source-note": HTMLElement;
  "coverage-note": HTMLElement;
  "sky-count": HTMLElement;
  "sky-map": HTMLElement;
  "sky-tooltip": HTMLElement;
  "period-distribution": HTMLElement;
  "distribution-note": HTMLElement;
  "catalogue": HTMLElement;
  "result-count": HTMLElement;
  "star-table": HTMLElement;
  "page-label": HTMLElement;
  "page-number": HTMLElement;
  "star-inspector": HTMLElement;
  "star-detail": HTMLElement;
  "analysis-section": HTMLElement;
  "analysis-star-name": HTMLElement;
  "lightcurve-notice": HTMLElement;
  "observation-count": HTMLElement;
  "observed-chart": HTMLElement;
  "observed-caption": HTMLElement;
  "folded-period": HTMLElement;
  "folded-chart": HTMLElement;
  "periodogram-card": HTMLElement;
  "fit-backend": HTMLElement;
  "fit-metrics": HTMLElement;
  "periodogram-chart": HTMLElement;
  "fit-caption": HTMLElement;
  "compute-lab": HTMLElement;
  "cluster-heading": HTMLElement;
  "cluster-state": HTMLElement;
  "cluster-progress-bar": HTMLElement;
  "cluster-progress-text": HTMLElement;
  "cluster-progress-percent": HTMLElement;
  "task-grid": HTMLElement;
  "cluster-results": HTMLElement;
  "cluster-metrics": HTMLElement;
  "ensemble-chart": HTMLElement;
  "cluster-result-note": HTMLElement;
  "cluster-idle-copy": HTMLElement;
  "cluster-error": HTMLElement;
  "parallel-fraction-label": HTMLElement;
  "processor-label": HTMLElement;
  "amdahl-speedup": HTMLElement;
  "gustafson-speedup": HTMLElement;
  "scaling-chart": HTMLElement;
  "methods": HTMLElement;
  "toast": HTMLElement;
  "fit-status": HTMLElement;
  "worker-results": HTMLElement;
  "sky-canvas": HTMLCanvasElement;
  "catalogue-export": HTMLAnchorElement;
  "search": HTMLInputElement;
  "min-period": HTMLInputElement;
  "max-period": HTMLInputElement;
  "parallel-fraction": HTMLInputElement;
  "processor-count": HTMLInputElement;
  "fit-min": HTMLInputElement;
  "fit-max": HTMLInputElement;
  "catalog-filter": HTMLSelectElement;
  "region-filter": HTMLSelectElement;
  "cluster-star": HTMLSelectElement;
  "cluster-workers": HTMLSelectElement;
  "cluster-tasks": HTMLSelectElement;
  "reset-filters": HTMLButtonElement;
  "prev-page": HTMLButtonElement;
  "next-page": HTMLButtonElement;
  "cluster-run": HTMLButtonElement;
  "fit-button": HTMLButtonElement;
  "export-fit": HTMLButtonElement;
  "export-cluster": HTMLButtonElement;
  "cluster-form": HTMLFormElement;
  "fit-form": HTMLFormElement;
}
export function $<K extends keyof Elements>(id: K): Elements[K];
export function $(id: string): HTMLElement;
export function $(id: string): HTMLElement {
 const node=document.getElementById(id);
 if (!node) throw new Error(`Missing interface element: ${id}`);
 return node;
}
export const errorMessage=(error: unknown): string => error instanceof Error ? error.message : String(error);
